readr-media/Sachiel

packages/politics-tracker/components/landing/Button.js, packages/politics-tracker/components/landing/Button.styled.js, packages/politics-tracker/components/landing/IconButton.js, packages/politics-tracker/components/landing/IconButton.styled.js
* 新增 landingpage會使用到的  Button component 
* 新增 landingpage會使用到的  IconButton component ( 含arrow_down icon)
=> feat(politics-tracker): add landingpage components ( Button&IconButton component)

packages/politics-tracker/README.md, packages/politics-tracker/graphql.d.ts, packages/politics-tracker/graphql/query/politics.graphql, packages/politics-tracker/next.config.js, packages/politics-tracker/package.json, yarn.lock
=> chore(politics-tracker): add GraphQL related settings

packages/politics-tracker/components/people/content-list.js, packages/politics-tracker/components/people/content-title.js, packages/politics-tracker/components/people/content.js, packages/politics-tracker/components/people/section-body-election.js, packages/politics-tracker/components/people/section-body-personal-file.js, packages/politics-tracker/components/people/section-body.js, packages/politics-tracker/components/people/section.js, packages/politics-tracker/pages/people/[id].js, packages/politics-tracker/styles/theme/index.js
[b0b4c1a](https://github.com/readr-media/Sachiel/pull/35/commits/b0b4c1a12c6f0b8fd6fba9a0319f5905aa95e21e): 修復出生日期、死亡日期的bug，若日期有缺漏則不顯示而非顯示`null`
[efbde03](https://github.com/readr-media/Sachiel/pull/35/commits/efbde03b2f4525320eda46ee946f85c378eec0ef): css 更新
[9f138f7](https://github.com/readr-media/Sachiel/pull/35/commits/9f138f77be8107e42d57128cb3d531bf4bdc65b3)：新增styled-component的custom theme
[389f013](https://github.com/readr-media/Sachiel/pull/35/commits/389f01311512284c9fe1c29a0c1a05e04aa1f9c7)：新增人物頁元件 `section-body-election`
=> feat(politics-tracker): add component `section-body-election` and fix problem of wrong date

packages/politics-tracker/Dockerfile, packages/politics-tracker/package.json, packages/politics-tracker/utils/utils.ts
修正頁面在使用 `getServerSideProps` 的情況下，使用 `tailwindcss/resolveConfig` 會導致出錯的情況。
=> fix(politics-tracker): server error when using tailwindcss/resolveConfig with SSR pre-render

packages/politics-tracker/components/header.module.css, packages/politics-tracker/components/nav.tsx, packages/politics-tracker/components/politics/section-list.module.css, packages/politics-tracker/components/politics/section-toggle.module.css, packages/politics-tracker/pages/election.tsx, packages/politics-tracker/pages/politics.tsx
* Add bottom `box-shadow` to header component
* Modify y-axis margin of section lists
* Modify style of control icon in section toggle, make it fixed on certain position
* Modify props type of href props of nav component, make it be compatible to `next/link`
=> refactor(politics-tracker): lots of style modification

packages/politics-tracker/components/landing/statistics-main.js, packages/politics-tracker/components/people/edit-button.js, packages/politics-tracker/components/people/section-toggle.js, packages/politics-tracker/utils/utils.ts
修正 type check 會出現 error 的程式碼 cc @dyfu95 @ChangRongXuan 
另外，發現有使用不存在的 key 的狀況，在 `packages/politics-tracker/components/people/edit-button.js`，
請 @dyfu95 再進行修正
=> fix(politics-tracker): code error with type checking

packages/politics-tracker/components/ga-script.tsx, packages/politics-tracker/components/layout/default.tsx, packages/politics-tracker/pages/index.jsx, packages/politics-tracker/pages/person/[id].js
因為不是所有的頁面都套用 DefaultLayout，
所以把 GA Script 抽出來用 component 處理，並加在所有頁面上
=> feat(politics-tracker): add GA to all pages

packages/politics-tracker/pages/person/[id].js
你那邊需要再對 margin 做調整，避免和 site header 及 nav 發生覆蓋的行為 cc @dyfu95
=> feat(politics-tracker): apply default layout and nav to person page

packages/politics-tracker/components/person/content-item.js, packages/politics-tracker/components/person/content-list.js, packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-content-contact.js, packages/politics-tracker/components/person/edit-content-item.js, packages/politics-tracker/components/person/edit-tags.js, packages/politics-tracker/components/person/section-body-personal-file.js, packages/politics-tracker/types/person.ts
[0cca2ba](https://github.com/readr-media/Sachiel/pull/77/commits/0cca2ba6bf50c576f285b86ae8ec1562e174fbba): 基本資料的編輯模式會帶入既有資料。
[493493b](https://github.com/readr-media/Sachiel/pull/77/commits/493493bb4b6da795a48034572dddcd0e4a4940af)：新增功能，可對編輯後的個人資料送出審核。
=> feat(politics-tracker/person): basic info will show exist value, user can edited and send data for review

packages/politics-tracker/pages/election.tsx, packages/politics-tracker/pages/index.jsx
* Change default election data handle
* Fix typo, `distinct` to `district`
=> refactor(politics-tracker): fix typo

packages/politics-tracker/.eslintrc.json, packages/politics-tracker/components/politics/add-politic-form.tsx, packages/politics-tracker/components/politics/politic-body.tsx, packages/politics-tracker/components/politics/politic-form.tsx, packages/politics-tracker/components/politics/react-context/politics-context.ts, packages/politics-tracker/components/politics/source-input.tsx
* Update ESLint rule, add `no-unused-vars` and `no-console` rules
* Fix ESLint warning codes
=> chore(politics-tracker): update eslint rule

packages/politics-tracker/components/landing/council-content.js, packages/politics-tracker/components/landing/council-main.js, packages/politics-tracker/components/landing/mayor-content.js, packages/politics-tracker/components/landing/mayor-main.js
=> fix(politics-tracker): fix toggle issues in landing page

packages/politics-tracker/components/landing/council-content.js, packages/politics-tracker/components/landing/council-main.js, packages/politics-tracker/components/landing/mayor-content.js, packages/politics-tracker/components/landing/mayor-main.js, packages/politics-tracker/pages/_document.tsx
* fix [ 補坑進度 ] 左側SideBar 的RWD 跑版問題
* fix [ 補坑進度 ] 候選人最後一位名稱的CSS右側無border線條
=> fix(politics-tracker): fix  UI/UX error in Mayor/Councilor components

packages/politics-tracker/components/person/edit-content-item.js, packages/politics-tracker/components/person/section-toggle.js, packages/politics-tracker/components/person/section.js, packages/politics-tracker/components/person/sources.js
[9c6a3ea](https://github.com/readr-media/Sachiel/pull/137/commits/9c6a3ea4c58a4f2ae6b0cf16901e79cdf464388a)：人物頁預設展開個人檔案
[4d0c596](https://github.com/readr-media/Sachiel/pull/137/commits/4d0c596b29d20785512709896aeba232a6e51d30)：修正input在手機版的破版問題
[74af945](https://github.com/readr-media/Sachiel/pull/137/commits/74af945a1a360e30283196b15afab3e3074b00bb)：修正toggle icon三角形大小
[f6a945d](https://github.com/readr-media/Sachiel/pull/137/commits/f6a945daa3fd98c7f6a1bdd58ce6916b91777e9d)：修正來源index，現在從1開始顯示而非0
=> style(politics-tracker/person): set stylesheet, open person info as default, set correct index of sources

packages/politics-tracker/components/person/edit-content-contact.js, packages/politics-tracker/components/person/section-body-election.js, packages/politics-tracker/components/person/section-toggle.js
* 調整：網站來源錯誤訊息文字
* 調整：「參與過的選舉」項目hover底線效果
=> fix(politics-tracker/person): adjust error-message content & hover effect

cloudbuild.yaml, packages/politics-tracker/.dockerignore, packages/politics-tracker/Dockerfile, packages/politics-tracker/README.md, packages/politics-tracker/constants/config.ts, packages/politics-tracker/pages/404.tsx, packages/politics-tracker/pages/_app.tsx
* Update Dockerfile with more stage
* Add `ENV` and environment related config
* Remove getInitialProps in _app
* Remove getStaticProps in 404
* Add `ENV` to cloudbuild
=> refactor(politics-tracker): add `ENV` and environment related config

packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-content-biography.js, packages/politics-tracker/components/person/edit-content-contact.js, packages/politics-tracker/components/person/edit-tags.js
* 表單驗證修正：如新增輸入欄位但無填值，目前設定為無法送出審核
=> fix(politics-tracker/person): form validation error handle

cloudbuild.yaml
This reverts commit b428086592a7cae9f14acd3b01ca16137b7dd937.
=> revert: "chore: update cloudbuild.yaml. Adopt kanoki cache in build stage

packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-source.js
* 人物頁 > 個人檔案 > [基本資料] 
1. 如無來源資訊，仍會自動抓取參選人姓名+呈現於表格內容中
2.如有更動表格內容但未填來源，才會顯示"來源必填" 的錯誤訊息
=> fix(politics-tracker/person): sources error-message error handle

packages/politics-tracker/components/politics/add-politic-form.tsx, packages/politics-tracker/components/politics/politic-body.tsx, packages/politics-tracker/components/politics/react-context/politics-context.ts, packages/politics-tracker/components/politics/react-context/use-politics.ts, packages/politics-tracker/components/politics/section-body.tsx
=> feat(politics-tracker/politic): add collaboration to waiting list

packages/politics-tracker/components/person/edit-content-item.js
人物頁fix: text field not working in safari
=> fix(politic-tracker/person): input(in safari)error handle

packages/politics-tracker/components/landing/council-content.js, packages/politics-tracker/components/landing/frontpage-button.js, packages/politics-tracker/components/landing/frontpage-title.js, packages/politics-tracker/components/landing/mayor-content.js, packages/politics-tracker/components/landing/mayor-main.js, packages/politics-tracker/components/landing/statistics-main.js
* 修正 heading 導致的 a11y 問題
* 修正 dom element 連結資訊錯誤使用的問題
=> fix(politics-tracker/landing): a11y issues

packages/politics-tracker/components/person/content-item.js, packages/politics-tracker/components/person/content-link.js, packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-source.js, packages/politics-tracker/components/person/section-body-personal-file.js, packages/politics-tracker/components/person/sources.js, packages/politics-tracker/components/politics/politic-block.tsx, packages/politics-tracker/components/politics/source-item.tsx, packages/politics-tracker/utils/utils.ts
* Remove unused imports
* Apply new source handle, supports url + description text format
=> refactor(politics-tracker): apply new source handle

packages/politics-tracker/components/politics/politic-block.module.css, packages/politics-tracker/components/politics/politic-content.module.css, packages/politics-tracker/components/politics/waiting-politic-block.module.css, packages/politics-tracker/utils/utils.ts
* Fix english word break issues
* Update text format of source meta
=> fix(politics-tracker/politic): english word break issues

packages/politics-tracker/components/nav.module.css, packages/politics-tracker/components/nav.tsx, packages/politics-tracker/graphql/query/politics/get-politics-related-to-person-elections.graphql, packages/politics-tracker/types/common.ts
* Nav 元件增加文字色彩設定參數 (`textColor` - 預設：`text-white`) cc @ChangRongXuan
=> feat(politics-tracker): add textColor option to nav component

packages/politics-tracker/components/nav.tsx, packages/politics-tracker/pages/election.tsx, packages/politics-tracker/pages/politics/[personId].tsx, packages/politics-tracker/pages/politics/detail/[politicId].js
目前只有人物資訊頁在 mobile 時不會有 Home，其他頁面在 mobile 時都會有 Home
=> fix(politics-tracker): behavior of home icon in nav

packages/politics-tracker/components/politics/add-politic-form.tsx, packages/politics-tracker/components/politics/button.module.css, packages/politics-tracker/components/politics/politic-body.module.css, packages/politics-tracker/components/politics/politic-body.tsx, packages/politics-tracker/components/politics/react-context/politics-context.ts, packages/politics-tracker/components/politics/react-context/use-politics.ts, packages/politics-tracker/components/politics/section-list.tsx, packages/politics-tracker/components/politics/title.module.css, packages/politics-tracker/graphql/query/politics/get-person-overview.graphql, packages/politics-tracker/pages/politics/[personId].tsx, packages/politics-tracker/tailwind.config.js, packages/politics-tracker/types/common.ts, packages/politics-tracker/types/politics.ts
待確認規格：政見進度狀態資訊的處理，是從政見進度資料中，抓取距離完成度最高的？還是抓取建立時間最新的資訊？或者是人工設定狀態？
目前實作規格：從政見進度中，抓取最新建立資訊的狀態，作為政見的進度狀態
=> feat(politics-tracker/politic): add status of politic progress

packages/politics-tracker/README.md, packages/politics-tracker/components/politics-detail/section.js, packages/politics-tracker/components/react-context/global.ts, packages/politics-tracker/components/react-context/use-global.ts, packages/politics-tracker/constants/config.ts, packages/politics-tracker/package.json, packages/politics-tracker/pages/election.tsx, packages/politics-tracker/pages/politics/detail/[politicId].js, yarn.lock
* feat(politics-tracker/politic-detail): add feedback form
* feat(politics-tracker): add `FEEDBACK_FORM_CONFIG` environment variable and global context
* fix(politics-tracker/election): code style
=> feat(politics-tracker/politic-detail): add feedback form to politic detail page

packages/politics-tracker/pages/politics/detail/[politicId].js
由於在頁面切換時，`getServerSideProps` 的運算結果會用 JSON 的方式輸出到前端頁面，
因此，`getServerSideProps` 運算回傳的資訊，盡可能是必要的資訊，這樣可以避免無謂的網路傳輸消耗。
- before
- after
JSON 資料傳輸減少超過 50%
cc @ChangRongXuan
=> refactor(politics-tracker/politic-detail): remove redundant props data

packages/politics-tracker/components/landing/council-content.js, packages/politics-tracker/components/landing/mayor-content.js
Mayor/Councilor 候選人姓名有缺漏：
bug問題在於沒有設定到候選人政見數=20的filter條件，目前已將「政見還很少」的filter條件從「政見數<20 && 政見數>0」 修正為「政見數<21 && 政見數>0」
=> fix(politics-tracker/Landing): fix candidates name error handle

packages/politics-tracker/components/politics-detail/progressbar.js, packages/politics-tracker/graphql/query/politics/get-politic-detail.graphql, packages/politics-tracker/graphql/query/politics/get-politics-related-to-person-elections.graphql, packages/politics-tracker/pages/politics/[personId].tsx, packages/politics-tracker/types/common.ts
由於 politic progress list 被移除，相關資訊轉移到 politic list 上，
調整與 politic progress 關聯的資料處理。
=> refactor(politics-tracker): update politic-progress list related handle

packages/politics-tracker/components/politics-detail/section-body-expert.js
`專家看點`修正：expert 頭像如來源onError，則顯示改為default-image。
=> fix(politics-tracker/politic-detail): expert default image error handle

.gitignore, packages/politics-tracker/Dockerfile, packages/politics-tracker/constants/config.ts, packages/politics-tracker/graphql/query/sitemap/get-elections.graphql, packages/politics-tracker/graphql/query/sitemap/get-people.graphql, packages/politics-tracker/graphql/query/sitemap/get-politics.graphql, packages/politics-tracker/next-sitemap.config.mjs, packages/politics-tracker/package.json, packages/politics-tracker/pages/server-sitemap.xml/index.tsx, packages/politics-tracker/tsconfig.json, packages/politics-tracker/types/common.ts, yarn.lock
* Add robots.txt and sitemap generation
* `compilerOptions#target` in tsconfig.json change from `es5` to `es2017` to support top-level await
=> feat(politics-tracker): add robots.txt and sitemap generation

packages/politics-tracker/README.md, packages/politics-tracker/constants/config.ts
以下三個環境變數移除 `NEXT_PUBLIC_` 的前綴
* `NEXT_PUBLIC_SITE_URL`
* `NEXT_PUBLIC_CMS_API_URL`
* `NEXT_PUBLIC_READR_CMS_API_URL`
調整為
* `SITE_URL`
* `CMS_API_URL`
* `READR_CMS_API_URL`
=> refactor(politics-tracker): remove NEXT_PUBLIC_ prefix from some environment variables
