readr-media/Sachiel

packages/politics-tracker/.babelrc, packages/politics-tracker/package.json, packages/politics-tracker/pages/people/[name].js, packages/politics-tracker/styles/theme/index.js, yarn.lock
- [cc02ebf](https://github.com/readr-media/Sachiel/pull/6/commits/cc02ebf0e40c440e555cbb99f6802cdc21d40abf): 新增`.babelrc`，讓styled-components不會在網頁重新整理後失效。
- [16f6c4f](https://github.com/readr-media/Sachiel/pull/6/commits/16f6c4f52d47ddcf8218b63c9a197d3e6e42b12c)：加入devDep `@types/styled-components`
- [095a980](https://github.com/readr-media/Sachiel/pull/6/commits/095a9801d23a0444f65468d18e0aac02103009ff)：在`/styles`底下新增一資料夾`/theme`，用來放styled-component的custom Theme設定
- [aa51382](https://github.com/readr-media/Sachiel/pull/6/commits/aa513820b128629698796f83b8733cd3ba2cef72)：新增頁面`/people/_name`
=> feat(politics-tracker): add `styled-component` and `ThemeProvider` setting

packages/politics-tracker/components/people/section-list.js, packages/politics-tracker/components/people/section-toggle.js, packages/politics-tracker/components/people/section.js, packages/politics-tracker/pages/people/[id].js, packages/politics-tracker/styles/theme/index.js
[a771f25](https://github.com/readr-media/Sachiel/pull/25/commits/a771f252c2c2b83f93ca175038c5a54c66a47d26): 新增一元件`Section`於人物頁。現在的元件父子關係為 `people/[id].js` -> `section` -> `section-list`
[c51a471](https://github.com/readr-media/Sachiel/pull/25/commits/c51a471dce016a707c2097be7ea2c125bf47b7ee)：重構元件`section-list`，讓子元件可以`children`的形式被傳入，提高元件在不同資料結構的復用性
=> 1016 refactor list

packages/politics-tracker/components/people/content.js, packages/politics-tracker/components/people/edit-button.js, packages/politics-tracker/components/people/edit-content.js, packages/politics-tracker/components/people/section-body-personal-file.js
[23a5e35](https://github.com/readr-media/Sachiel/pull/40/commits/23a5e352a4d0d020af5ff8ae51e13f2de59dacee):新增元件`edit-content`，用於各content的編輯模式。
[0b652d0](https://github.com/readr-media/Sachiel/pull/40/commits/0b652d0f659da3bb3e0fe47e223a9960acbdf44e)：重構元件，讓`edit-content`可在`section-body-personal-file.js`中被重用
=> feat(politics-tracker/people): add `edit-content` and refactor `section-body-personal-file.js`

packages/politics-tracker/components/politics/politic-form.tsx, packages/politics-tracker/types/common.ts, packages/politics-tracker/utils/utils.ts
將一些用於處理字串與陣列的函式移至`/utils`，以便共用
=> refactor(politics-tracker): move function from `politics-form` to `utils`

packages/politics-tracker/components/person/add-input-button.js, packages/politics-tracker/components/person/content-item.js, packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-content-item.js, packages/politics-tracker/components/person/section-body-personal-file.js, packages/politics-tracker/components/person/sources.js, packages/politics-tracker/types/person.ts, packages/politics-tracker/utils/utils.ts
[fb28ba0](https://github.com/readr-media/Sachiel/pull/59/commits/fb28ba0b5fa1ebb8f5e61d881c649d4539646ff2): 使用utils function，將字串格式的source轉為陣列。
[09541da](https://github.com/readr-media/Sachiel/pull/59/commits/09541da9996e2a5894bd6c152e10615012918778)：將utils function `stringToSources`新增一變數delemiter，並設定預設值，以重複用於包含不同分行格式的字串
[e303ed8](https://github.com/readr-media/Sachiel/pull/59/commits/e303ed8d8def04c9894a685777fcdac2f388f83a)：人物頁新增功能：可以編輯與刪除來源
[ddbcfef](https://github.com/readr-media/Sachiel/pull/59/commits/ddbcfefe7524692f4556049869f6317c6cf103dd)：新增來源的標題：`來源（必填）`
[77c5582](https://github.com/readr-media/Sachiel/pull/59/commits/77c5582f0dabcd453fbfc202ff3d58765d760615)：新增元件`add-input-button`，用於新增編輯模式下的各個項目內容，如來源、經歷等。功能尚未實作
=> 1018 source input 2

packages/politics-tracker/components/person/add-input-button.js, packages/politics-tracker/components/person/content-item.js, packages/politics-tracker/components/person/content-link.js, packages/politics-tracker/components/person/content-list.js, packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-content-biography.js, packages/politics-tracker/components/person/edit-content-contact.js, packages/politics-tracker/components/person/section-body-personal-file.js, packages/politics-tracker/components/person/sources.js, packages/politics-tracker/components/politics/source-input.tsx, packages/politics-tracker/types/person.ts
- [7714657](https://github.com/readr-media/Sachiel/pull/62/commits/7714657590ffae2722691004bd1a36bc666211eb):使用utils function將字串轉為陣列
- [1093b1a](https://github.com/readr-media/Sachiel/pull/62/commits/1093b1a63bee6d0f11fa27cedcb2f7462796342f)：調整元件`components/politics/source-input.tsx`，新增一傳入變數placeholder，以調整input placeholder的值（預設為`'網址, 選舉公報...'`
- [8356958](https://github.com/readr-media/Sachiel/pull/62/commits/8356958dc059094f35dc7e30b74aefb95a26afa5)：新增元件`edit-content-biography`，用於經歷欄位的編輯模式
- [e2d4a38](https://github.com/readr-media/Sachiel/pull/62/commits/e2d4a387eee720333ccb2997eb327c1e1944f360)：調整content-item，使其可以顯示多藍內容
- [61f13a9](https://github.com/readr-media/Sachiel/pull/62/commits/61f13a9268e89b3c36b87b4e363a90d468c69c98)：新增元件 `edit-content-contact`，用於聯絡方式欄位的編輯模式
=> feat(politics-tracker/person): add component for edit mode

packages/politics-tracker/components/person/content.js, packages/politics-tracker/components/person/edit-content-basic.js, packages/politics-tracker/components/person/edit-content-biography.js, packages/politics-tracker/components/person/edit-content-contact.js, packages/politics-tracker/components/person/edit-send-or-cancel.js, packages/politics-tracker/components/person/edit-source.js, packages/politics-tracker/components/person/edit-tags.js, packages/politics-tracker/components/person/section-body-personal-file.js, packages/politics-tracker/graphql/mutation/person/add-person-to-thread.graphql, packages/politics-tracker/graphql/mutation/person/create-person.graphql
[a542151](https://github.com/readr-media/Sachiel/pull/69/commits/a542151ed3018c7021b7af4041843390d9f809cd): 重構元件，讓編輯模式的送出審核按鈕可吃到編輯後的資料。
[3fab94c](https://github.com/readr-media/Sachiel/pull/69/commits/3fab94c05e97b32e51db207639e2672ce1cd1423)：新增用於人物頁的gql mutation。
[a1f3801](https://github.com/readr-media/Sachiel/pull/69/commits/a1f3801d56ea265b0806b469e15da6873100e02a)：新增人物頁個人檔案「經歷」及「聯絡方式」的mutation。
=> feat(politics-tracker/person): add feature of send mutation of `biography`, `contact` info

packages/politics-tracker/components/icon.tsx, packages/politics-tracker/components/nav.tsx, packages/politics-tracker/components/politics/section-body.tsx, packages/politics-tracker/components/politics/title.module.css, packages/politics-tracker/components/politics/title.tsx, packages/politics-tracker/pages/politics/[personId].tsx, packages/politics-tracker/types/common.ts, packages/politics-tracker/types/politics.ts
* Fix politics#title wording [政見頁 wording 修改](https://app.asana.com/0/1203213267790681/1203234221156472/f)
* Fix politics#section-body default wording [政見頁 wording 修改](https://app.asana.com/0/1203213267790681/1203234221156472/f)
* Update politics#nav back wording [政見頁回人物頁的相關 UI 修改](https://app.asana.com/0/1203213267790681/1203225447575569/f)
* Add href prop to Icon component [政見頁回人物頁的相關 UI 修改](https://app.asana.com/0/1203213267790681/1203225447575569/f)
* Add link to politics#title personal image and name [政見頁回人物頁的相關 UI 修改](https://app.asana.com/0/1203213267790681/1203225447575569/f)
=> feat(politics-tracker): add href prop to icon component

packages/politics-tracker/components/politics/source-input.module.css
修正 `.minus`的css 設定，將`flex`改為`block`，並刪除`flex`的相關設定
=> fix(politics-tracker): unable show `Minus` icon in `source-input` at mobile

packages/politics-tracker/components/ga-script.tsx, packages/politics-tracker/components/layout/default.tsx, packages/politics-tracker/next.config.js, packages/politics-tracker/pages/_app.tsx, packages/politics-tracker/pages/index.jsx
看起來 `NEXT_PUBLIC_` 的運作方式是會在 build time 時就用 inline 的方式處理，
而在 build 時沒有相關環境變數的資訊，所以輸出來的網頁是 undefined，
如果是要在 runtime 且是在前端頁面變動的設定，
需要用 `next.config.json#publicRuntimeConfig` 的方式來處理
=> fix(politics-tracker): GA tracking ID missing issue

packages/politics-tracker/package.json, packages/politics-tracker/pages/election.tsx, yarn.lock
- upgrade @readr-media/react-election-votes-comparison to @2.0.0-beta.3
因為縣市議員部分的資料還沒有 migrate 到 v2 版本，所以 PR 中有些程式碼是為了補足 v1 版本缺少的資料。
=> refactor(pt): upgrade election-votes-comparison pkg to latest

packages/politics-tracker/components/landing/council-content.js, packages/politics-tracker/components/landing/mayor-content.js, packages/politics-tracker/package.json, packages/politics-tracker/pages/election.tsx, yarn.lock
修正 mobile 版型下，縣市長與議員的區域展開功能，會與候選人名稱個別連結在點擊事件上處理產生衝突的情況。
成因：
由於候選人名稱連結在 DOM tree 結構上是包覆在區域的容器底下，當點擊 event 從候選人名稱往上 bubble 時，
被區域容器的點擊監聽處理，整個區域容器被關閉，導致候選人名稱點擊的事件被清除，於是不會跳轉到候選人的政見頁。
cc @ChangRongXuan 
ref: [React: Event Bubbling and Capturing](https://www.robinwieruch.de/react-event-bubbling-capturing/)
=> fix(politics-tracker/landing): toggle and link click event collision issues

packages/politics-tracker/components/politics-detail/progressbar.js, packages/politics-tracker/graphql/query/politics/get-politic-detail.graphql
1) 調整 `get-politic-detail.graphql` ，新增 politics > person > elected，取得該候選人該次選舉是否當選data。
2) 調整 `progressbar.js` ，新增 elected 的boolean條件判斷，如 elected為false 則顯示「未當選」進度條設計樣式。
=> fix(politics-tracker/politic-detail): adjust progress-bar elected fix(politics-tracker/politic-detail): adjust progress-bar elected false status

packages/politics-tracker/graphql/query/politics/get-politic-detail.graphql
調整 `get-politic-detail.graphql`：politics > expertPoint 新增orderBy條件：reviewDate: desc，越近期發表的專家看點(expertPoint)會排列於專家區塊較上方。（由上到下=>由近到遠）
=> chore(politics-tracker/politic-detail): adjust GQL(expert order by reviewDate: desc)

packages/politics-tracker/pages/politics/detail/[politicId].js
調整 `[politicId].js`
1) 透過 person_id (候選人id)取得 personElections 裡歷屆參與過的選舉。
2) 取得最新一筆election type作為props傳入<Title>component，資訊與政見總覽頁同步。
=> fix(politics-tracker/politic-detail): adjust campaign data in <Title> component

packages/politics-tracker/components/politics-detail/progressbar.js, packages/politics-tracker/components/politics-detail/section-title.js, packages/politics-tracker/components/politics-detail/section.js, packages/politics-tracker/graphql/query/politics/get-politic-detail.graphql, packages/politics-tracker/pages/politics/detail/[politicId].js, packages/politics-tracker/types/politics-detail.ts
單一政見頁修正：
1) 進度條：當候選人沒有得票數data( `politics>person>votes_obtained_number`) 時，視為選舉尚未結束 => 進度條不會顯示。
2) 進度條：當該屆選舉已結束，顯示進度條，並進行是否當選Boolean判斷( `politics>person>elected`)。如有當選，則顯示未開始/進行中/已完成 ; 如未當選，則顯示未當選。
3) 候選人黨籍如為「無黨籍」，從無顯示資訊修正為顯示：「無黨籍」。
=> fix(politics-tracker/politic-detail): progress-bar error handle

packages/politics-tracker/pages/index.jsx
1. `yarn add moment-timezone`
2. 因「Readr文章日期」與「政見/LandingPage相關報導的文章日期」會有時區差異( 未過 08:00 則會差一天），故在取回的Readr CMS data加上 `moment().tz('Asia/Taipei')`時區轉換。
=> fix(politics-tracker/Landing): moment-timezone error handle

packages/politics-tracker/pages/politics/detail/[politicId].js
調整：
1) 傳入<Title>的候選人選舉類型data，因`personAllElections`的`election`( = 候選人歷屆參與過的選舉），排序上是越新參與的選舉index值越大。故調整data取值為`personAllElections[personAllElections.length - 1].election.type`，取得最新一筆候選人參選的選舉資訊。
2) 調整後部分單一政見頁與政見總覽頁在「參選類型」上的不同步狀況已解決。
=> fix(politics-tracker/politic-detail): <Title> election type data error handle

packages/politics-tracker/components/custom-head.tsx, packages/politics-tracker/pages/_app.tsx, packages/politics-tracker/pages/_document.tsx, packages/politics-tracker/pages/politics/[personId].tsx
調整：
1) `pages/politics/[personId.tsx]` ：新增「政見總覽頁」的`<Head>`與相應的`title/description`資訊。
2) 將 `CustomHead`裡 `title/description` 的資訊，移至`pages/_app.tsx`：
- 對於通用頁籤的資訊，原設定於`components/custom-head.tsx`中，並export `<CustomHead>` 至`pages/_document.tsx`中做設定。
- 因專案需求改為「不同頁面有各自頁籤」，在參考[官方文件](https://nextjs.org/docs/messages/no-document-title)後，將通用頁籤的 `title/description` 移至 `pages/_app.tsx`。（因 `_document.tsx` only rendered on the initial pre-render，當切換至其他頁面再跳回首頁時，原首頁的`title/description` 會無法顯示，移至`_app.tsx`後可解決此狀況。）
=> feat(politics-tracker): move custom <Head> title/description to _app.tsx

packages/politics-tracker/pages/person/[id].js, packages/politics-tracker/pages/politics/detail/[politicId].js
調整：將原本頁面各自設定的`<Head>`，調整為`<CustomHead>`元件。僅需將各頁面的`title/description`資訊，作為props傳入`<CustomHead>`，即可設定該頁面特定的`title/description`資訊。
=> fix(politics-tracker): change <Head> to <CustomHead>

packages/politics-tracker/pages/_app.tsx, packages/politics-tracker/pages/index.jsx
調整：
1) 移除原 `pages/_app.tsx` 的`<CustomHead>`，避免各頁面與`_app.tsx`對於 og:title 的重複render。
2) 於 `pages/index.jsx` 新增 `<CustomHead>`。
=> fix(politics-tracker): og:title error handle
